INFO:     Will watch for changes in these directories: ['/home/james/Desktop/threatcluster/cluster/admin-web']
INFO:     Uvicorn running on http://127.0.0.1:8002 (Press CTRL+C to quit)
INFO:     Started reloader process [71985] using WatchFiles
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 234, in prepare
    _fixup_main_from_name(data['init_main_from_name'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 258, in _fixup_main_from_name
    main_content = runpy.run_module(mod_name,
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/james/Desktop/threatcluster/cluster/admin-web/app/main.py", line 20, in <module>
    from app.routes import auth, dashboard, pipeline, monitoring, entities, maintenance
  File "/home/james/Desktop/threatcluster/cluster/admin-web/app/routes/entities.py", line 14, in <module>
    from cluster.database.models import Entity, EntityType, Article, ArticleEntity
ModuleNotFoundError: No module named 'cluster.database.models'
Loaded .env from /home/james/Desktop/threatcluster/.env
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/main.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/main.py'. Reloading...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 234, in prepare
    _fixup_main_from_name(data['init_main_from_name'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 258, in _fixup_main_from_name
    main_content = runpy.run_module(mod_name,
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/james/Desktop/threatcluster/cluster/admin-web/app/main.py", line 71, in <module>
    app.include_router(auth.router, tags=["auth"])
NameError: name 'auth' is not defined. Did you mean: 'oauth'?
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
WARNING:  WatchFiles detected changes in 'app/main.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
Loaded .env from /home/james/Desktop/threatcluster/.env
WARNING:  WatchFiles detected changes in 'app/main.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "main".
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
Loaded .env from /home/james/Desktop/threatcluster/.env
WARNING:  WatchFiles detected changes in 'main.py'. Reloading...
Process SpawnProcess-29:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/james/Desktop/threatcluster/cluster/admin-web/main.py", line 14, in <module>
    from app.main import app
  File "/home/james/Desktop/threatcluster/cluster/admin-web/app/routes/../../../../backend-api/app/main.py", line 12, in <module>
    from app.core.config import get_settings
ImportError: cannot import name 'get_settings' from 'app.core.config' (/home/james/Desktop/threatcluster/cluster/admin-web/app/core/config.py)
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
Loaded .env from /home/james/Desktop/threatcluster/.env
WARNING:  WatchFiles detected changes in 'app/main.py'. Reloading...
Process SpawnProcess-30:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/james/Desktop/threatcluster/cluster/admin-web/main.py", line 14, in <module>
    from app.main import app
  File "/home/james/Desktop/threatcluster/cluster/admin-web/app/routes/../../../../backend-api/app/main.py", line 12, in <module>
    from app.core.config import get_settings
ImportError: cannot import name 'get_settings' from 'app.core.config' (/home/james/Desktop/threatcluster/cluster/admin-web/app/core/config.py)
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
Loaded .env from /home/james/Desktop/threatcluster/.env
WARNING:  WatchFiles detected changes in 'main.py'. Reloading...
Process SpawnProcess-31:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/james/Desktop/threatcluster/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/james/Desktop/threatcluster/cluster/admin-web/main.py", line 20, in <module>
    from app.main import app
  File "/home/james/Desktop/threatcluster/cluster/admin-web/app/routes/../../../../backend-api/app/main.py", line 12, in <module>
    from app.core.config import get_settings
ImportError: cannot import name 'get_settings' from 'app.core.config' (/home/james/Desktop/threatcluster/cluster/admin-web/app/core/config.py)
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
Loaded .env from /home/james/Desktop/threatcluster/.env
WARNING:  WatchFiles detected changes in 'app/routes/entities.py'. Reloading...
INFO:     Started server process [100478]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'app/routes/pipeline.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [100478]
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
Loaded .env from /home/james/Desktop/threatcluster/.env
Auth0 Domain: dev-mazc2h57lknel3yr.uk.auth0.com
Auth0 Client ID: KLzhVYbuDcfG7I08XgBGu4wW0V5XVZla
Auth0 Client Secret: ****************************************************************
Auth0 Callback URL: http://localhost:8002/callback
Starting ThreatCluster Admin on 127.0.0.1:8002
Shutting down...
INFO:     Started server process [100713]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
